### ISSUE TITLE
뽐뿌 쿠폰게시판에서 사용할 수 있게 만들어주세요.

### ISSUE THREAD

**Issue by 20eung** [stateofai/naver-paper#1]
안녕하세요.
클리앙에 올리신 게시글을 보고 따라서 만들어봤습니다.
지금까지는 잘 동작하는 것 같습니다. 

다만 Google Cloud VM에서 cronjob으로 실행시키는데 네이버에서 새로운 로그인 알림 이메일이 계속해서 오네요. 이것은 어떻게 해야할지 몰라서 이메일 분류 설정에서 삭제처리하고 있습니다.

며칠 사이에 파이썬 코드를 완전히 고치셨네요.

github에 올리셨던 초기 코드를 참고하여 뽐뿌 쿠폰게시판에서도 사용할 수 있게 만들었습니다. ChatGPT를 하루종일 고문하였습니다^^

실력이 좋으시니 맘만 먹으면 금방 만드실 수 있으시겠으나 참고하시라고 글 남깁니다.

https://github.com/20eung/naverpaper

**Comment by stateofai** [comment]
@20eung 님, 감사합니다. 참고해서 수정할게요!

**Comment by stateofai** [comment]
#12 
Thanks to @bluesid
