### ISSUE TITLE
GitHub Action 만들기

### ISSUE THREAD

**Issue by stateofai** [stateofai/naver-paper#10]
WIP

**Comment by stateofai** [comment]
완료

**Comment by isul** [comment]
와우~~ 점점 발전하네요.. 덕분에 포인트 잘 쌓이고 있습니다. 고맙습니다.

**Comment by bagng** [comment]
추가로 Action에 로그를 지우시려면 다음과 같이 하시면 됩니다. (ubuntu 기준으로 설명드립니다.)
Github CLI를 설치해서 지워야 합니다. 추가로 auth key를 미리 만들어 놓으셔야 합니다.
auth key는 [Settings]-[Developer Settings]-[Personal access tokens] 에서 만드시면 됩니다.
auth key에서 repo와 read:org를 체크하셔야 합니다. 저는 repo를 전부 체크하고 admin:org도 모두 체크했습니다.
아래의 사이트를 참조하십시오.
(https://velog.io/@daelkdev/SOLUTION-GitHub-%ED%86%A0%ED%81%B0-%EA%B4%80%EB%A6%AC%EB%A5%BC-%EC%9C%84%ED%95%9C-gh-%EC%84%A4%EC%B9%98-%EB%B0%8F-%EB%A1%9C%EA%B7%B8%EC%9D%B8)

1. gh 설치
$ sudo apt-get install gh

2. gh 로 github 로그인 하기
$ gh auth login
What account do you want to log into?
GitHub.com을 선택
What is your preferred protocol for Git operations?
SSH를 선택
Upload your SSH public key to your GitHub account?
Skip을 선택
How would you like to authenticate GitHub CLI?
"Paste an authentication token"을 선택
? Paste your authentication token:
만들어진 auth key를 입력합니다.

3. action 결과 지우는 명령어 입력하기
다음과 같이 명령을 입력하시면 됩니다.
user=[Github 아이디] repo=[Repo 이름]; gh api repos/$user/$repo/actions/runs \
--paginate -q '.workflow_runs[] | select(.head_branch != "master") | "\(.id)"' | \
xargs -n 1 | xargs -i % gh api repos/$user/$repo/actions/runs/% -X DELETE

도움되시기 바랍니다.

**Comment by stateofai** [comment]
@bagng 님, 감사합니다!

**Comment by bagng** [comment]
안녕하세요.

제가 테스트 해보니 로그를 전부 지우는 경우 로그인 오류가 나는 경우가 생깁니다.
마지막 로그만 남기고 지우면 문제가 발생하지 않는 것 같습니다.

마지막 로그만 남기고 지우는 스크립트 올려드립니다.
참조하시기 바랍니다.
17라인에 [REPO NAME]에 repo 이름을 적으시고
18라인에 [github ID]에 github id를 넣으시면 됩니다.

---------------------------------------------------------------------------------
#
# This script uses the  github command line tool
# to delete the last 30 logs from your repository's workflow runs
#
# Requirements
#
# gh - github command line (brew install gh)
# you will need a GH_TOKEN, create it here: https://github.com/settings/tokens
#
# once you've created the personal access token with permission to manage your workflows
# you gotta tell gh which repository it's working with using
# $ gh repo set-default
# you will be presented an interactive list to pick the repo you want to delete workflow logs from

# jq - json command line processor (brew

repo=[REPO NAME]
user=[github ID]

WORKFLOW_RUN_IDS=$(gh api /repos/${user}/${repo}/actions/runs | jq -r ".workflow_runs[] | [.id] | @tsv")

count=1

for id in ${WORKFLOW_RUN_IDS}
do
    #echo "${count} Workflow ID: ${id}"
    if [ $count = 1 ]
    then
        echo "first not delete. ${id}"
    else
        echo "Delete ${id}"
        gh api -X DELETE "/repos/${user}/${repo}/actions/runs/${id}"
    fi

    count=$((count+1))
#    gh api -X DELETE "/repos/${user}/${repo}/actions/runs/${id}"
done
---------------------------------------------------------------------------------
