### ISSUE TITLE
다모앙 지원

### ISSUE THREAD

**Issue by dongbum** [stateofai/naver-paper#18]
현재 클리앙 사태 때문에 많은 유저가 다모앙이라는 임시 대피소로 이전한 상태입니다.

다모앙의 알뜰구매 게시판도 크롤링 할 수 있으면 좋겠습니다.

https://damoang.net

**Comment by isul** [comment]
아래에 이 소스를  포크하여 수정한 코드에서 다모앙을 지원합니다.
https://github.com/isul/naver-paper/blob/main/src/usr/local/app/main.py
기존 네이버 관련 코드에서 크게 수정된 건 없습니다.
stateofai님께서 적용해주시면 좋을 듯합니다.

**Comment by dongbum** [comment]
> 아래에 이 소스를 포크하여 수정한 코드에서 다모앙을 지원합니다. https://github.com/isul/naver-paper/blob/main/src/usr/local/app/main.py 기존 네이버 관련 코드에서 크게 수정된 건 없습니다. stateofai님께서 적용해주시면 좋을 듯합니다.

와우 감사합니다.

isul 님이 Pull requests 로 올려주시면 머지될듯합니다. :-)
