### ISSUE TITLE
최근에 "session.py" line 82에서 에러가 발생됩니다.

### ISSUE THREAD

**Issue by isul** [stateofai/naver-paper#4]
최근에 아래와 같은 에러가 발생됩니다.
"session.py", line 82, in session
     finalize_url = re.search(
 AttributeError: 'NoneType' object has no attribute 'group'

아래 코드에서 발생하는 것 같습니다.
finalize_url = re.search(
            r'location\.replace\("([^"]+)"\)', response.content.decode("utf-8")
        ).group(1)

"https://nid.naver.com/nidlogin.login" 호출한 응답 내용이 바뀌어서 발생하는 문제일까요?

**Comment by stateofai** [comment]
바뀌었나보네요. 확인 후 조치할게요!

**Comment by monolith-youjunghong** [comment]
오 저도 같은 이슈가 발생하고 있습니다!

**Comment by stateofai** [comment]
@isul 님, 이거 해결이 쉽지 않네요 ㅜㅜ 랜덤하게 captcha 가 뜨는데 시간이 좀 소요될 거 같습니다..

**Comment by 5Ethanoh** [comment]
애타게 기다리고 있겠습니다!

**Comment by icebluejean** [comment]
> 애타게 기다리고 있겠습니다!
헉 닉네임 마저 애가 타네요 ㄷㄷ
이거 해결은 힘들까요
저도 애타는중..

**Comment by dongbum** [comment]
진척이 있나요? :grinning:

**Comment by bagng** [comment]
안녕하세요.

제가 작성한 윈도우에서 Selenium으로 로그인하는 버전 보내드립니다.
사용하는 크롬 버전은 120이고 해당하는 chrome-driver 링크는 아래와 같습니다.
https://edgedl.me.gvt1.com/edgedl/chrome/chrome-for-testing/120.0.6099.109/win64/chromedriver-win64.zip

requirements.txt는 첨부 파일로 올려드립니다.
[requirements.txt](https://github.com/stateofai/naver-paper/files/13958896/requirements.txt)

python 코드입니다.
-------------------------------------------------------------------------------------------------------------------------------
from selenium import webdriver
from selenium.webdriver.chrome.service import Service
from webdriver_manager.chrome import ChromeDriverManager
from selenium.webdriver.common.by import By
import time
import requests
from urllib.parse import urljoin

from bs4 import BeautifulSoup

def find_naver_campaign_links(base_url, visited_urls_file='visited_urls.txt'):
    # Read visited URLs from file
    try:
        with open(visited_urls_file, 'r') as file:
            visited_urls = set(file.read().splitlines())
    except FileNotFoundError:
        visited_urls = set()

    # Send a request to the base URL
    response = requests.get(base_url)
    soup = BeautifulSoup(response.text, 'html.parser')

    # Find all span elements with class 'list_subject' and get 'a' tags
    list_subject_links = soup.find_all('span', class_='list_subject')
    naver_links = []
    for span in list_subject_links:
        a_tag = span.find('a', href=True)
        if a_tag and '네이버' in a_tag.text:
            naver_links.append(a_tag['href'])

    # Initialize a list to store campaign links
    campaign_links = []

    # Check each Naver link
    for link in naver_links:
        full_link = urljoin(base_url, link)
        print("naver_links - " + full_link)
        if full_link in visited_urls:
            continue  # Skip already visited links

        res = requests.get(full_link)
        inner_soup = BeautifulSoup(res.text, 'html.parser')

        # Find all links that start with the campaign URL
        for a_tag in inner_soup.find_all('a', href=True):
            if a_tag['href'].startswith("https://campaign2-api.naver.com"):
                campaign_links.append(a_tag['href'])

        # Add the visited link to the set
        visited_urls.add(full_link)

    # Save the updated visited URLs to the file
    with open(visited_urls_file, 'w') as file:
        for url in visited_urls:
            file.write(url + '\n')

    return campaign_links

# 크롬 드라이버 옵션 설정
chrome_options = webdriver.ChromeOptions()

# 새로운 창 생성
driver = webdriver.Chrome(service=Service(ChromeDriverManager().install()), options=chrome_options)
driver.get('https://naver.com')

# 현재 열려 있는 창 가져오기
current_window_handle = driver.current_window_handle

# <a href class='MyView-module__link_login___HpHMW'> 일때 해당 링크 클릭
driver.find_element(By.XPATH, "//a[@class='MyView-module__link_login___HpHMW']").click()

# 새롭게 생성된 탭의 핸들을 찾습니다
# 만일 새로운 탭이 없을경우 기존 탭을 사용합니다.
new_window_handle = None
for handle in driver.window_handles:
    if handle != current_window_handle:
        new_window_handle = handle
        break
    else:
        new_window_handle = handle

# 새로운 탭을 driver2로 지정합니다
driver.switch_to.window(new_window_handle)
driver2 = driver

username = driver2.find_element(By.NAME, 'id')
pw = driver2.find_element(By.NAME, 'pw')

input_id="#naver_id"
input_pw="#password"

# ID input 클릭
username.click()
# js를 사용해서 붙여넣기 발동 <- 왜 일부러 이러냐면 pypyautogui랑 pyperclip를 사용해서 복붙 기능을 했는데 운영체제때문에 안되서 이렇게 한거다.
driver2.execute_script("arguments[0].value = arguments[1]", username, input_id)
time.sleep(1)

pw.click()
driver2.execute_script("arguments[0].value = arguments[1]", pw, input_pw)
time.sleep(1)

#입력을 완료하면 로그인 버튼 클릭
driver2.find_element(By.CLASS_NAME, "btn_login").click()
time.sleep(1)

# The base URL to start with
base_url = "https://www.clien.net/service/board/jirum"
#base_url = "https://www.clien.net/service/board/park"

campaign_links = find_naver_campaign_links(base_url)
if(campaign_links == []):
    print("모든 링크를 방문했습니다.")
for link in campaign_links:
    print(link) # for debugging
    # Send a request to the base URL
    driver2.get(link)
    try:
        result = driver2.switch_to.alert
        print(result.text)
        result.accept()
    except:
        print("no alert")
        pageSource = driver2.page_source
        print(pageSource)
    time.sleep(1)

time.sleep(10)
---------------------------------------------------------------------------------------------------------------------------

**Comment by seongilp** [comment]
@bagng 님, 코드 잘 작동하네요! 머지 시켜놓겠습니다

**Comment by 5Ethanoh** [comment]
@bagng 잘 동작하네요 감사합니다!!

**Comment by kty0113** [comment]
혹시 리눅스 서버에서는 pywin32 를 사용할수 없나요?

**Comment by dongbum** [comment]
> 혹시 리눅스 서버에서는 pywin32 를 사용할수 없나요?

헛... 이 코드 이제 리눅스에서 작동 안하는건가요?

**Comment by kty0113** [comment]
> > 혹시 리눅스 서버에서는 pywin32 를 사용할수 없나요?
> 
> 헛... 이 코드 이제 리눅스에서 작동 안하는건가요?

저도 설치가 안되길래 찾아봤는데, 리눅스에서는 사용이 안된다는 말이 보여서 질문해봤습니다.

**Comment by isul** [comment]
저도  pywin32 관련 에러가 발생됩니다.
pywin32 에러와 상관없이 변경된 코드가 linux에서 headless 모드로 동작되는 것인지도 궁금합니다.

**Comment by stateofai** [comment]
@isul 리눅스에서도 headless 모드로 작동합니다.
@kty0113 @dongbum 리눅스에서 사용 가능합니다

**Comment by bagng** [comment]
> @isul 리눅스에서도 headless 모드로 작동합니다. @kty0113 @dongbum 리눅스에서 사용 가능합니다

windows에서는 headless 모드로 동작시 다음과 같은 오류가 발생합니다.
[0122/090347.097:INFO:CONSOLE(2)] "Failed to execute 'postMessage' on 'DOMWindow': The target origin provided ('https://shopsquare.naver.com') does not match the recipient window's origin ('https://www.naver.com').", source: https://pm.pstatic.net/resources/js/main.5e714c50.js?o=www (2)
[0122/090348.182:INFO:CONSOLE(0)] "[.WebGL-0000031C02C7DC00]GL Driver Message (OpenGL, Performance, GL_CLOSE_PATH_NV, High): GPU stall due to ReadPixels", source: https://nid.naver.com/nidlogin.login?mode=form&url=https://www.naver.com/ (0)

headless 옵션을 지우고 사용하면 문제가 없습니다.
참조하십시오.

**Comment by stateofai** [comment]
@bagng 님, 한번 살펴볼게요!

**Comment by kty0113** [comment]
> @isul 리눅스에서도 headless 모드로 작동합니다. @kty0113 @dongbum 리눅스에서 사용 가능합니다

OCI 에서 사용하고 있었는데, 서버 완전 삭제하고 
리눅스(Ubuntu 22.04) 로 다시 세팅하니 잘됩니다. 감사합니다.

**Comment by isul** [comment]
> @isul 리눅스에서도 headless 모드로 작동합니다. @kty0113 @dongbum 리눅스에서 사용 가능합니다

도커로 alpine 리눅스에서 돌아가게 했습니다.
headless 모드로 잘 동작되는 것 같습니다. 네이버 로그인은 됩니다.
아직 클리앙에 링크가 올라오지 않아서 모든 상황을 확인하지는 못했네요.
모두 성공적으로 처리되면 수정한 코드와 도커 이미지를 공유하겠습니다.
고맙습니다.

**Comment by dongbum** [comment]
@stateofai 저는 데비안12 에서 돌려보려니 ChromeDriver 부분에서 막히네요..
현재는 윈도우에서 쓰고 있습니다. ㅎㅎㅎ

@isul 도커 이미지 기대하고 있겠습니다. 화이팅!

**Comment by isul** [comment]
> @stateofai 저는 데비안12 에서 돌려보려니 ChromeDriver 부분에서 막히네요.. 현재는 윈도우에서 쓰고 있습니다. ㅎㅎㅎ
> 
> @isul 도커 이미지 기대하고 있겠습니다. 화이팅!

크롬 드라이버 따로 설치했으면 아래 코드로 수정해서 사용해보세요.

```
    # 새로운 창 생성
    driver = webdriver.Chrome(options=chrome_options)
    driver.get('https://naver.com')
```

포인트 적립되면 공유하겠습니다^^

**Comment by isul** [comment]
도커 이미지입니다. 아래 링크에 설명 포함되어 있습니다.
https://hub.docker.com/r/isul/naver-pay-picker

변경된 소스코드도 이곳에 곧 공개하겠습니다.

**Comment by stateofai** [comment]
GitHub Action 으로도 실행 가능하도록 변경되었습니다.
서버에서 실행할 필요없이 간편하게 GitHub Action 으로 실행해보세요~

**Comment by dongbum** [comment]
> GitHub Action 으로도 실행 가능하도록 변경되었습니다. 서버에서 실행할 필요없이 간편하게 GitHub Action 으로 실행해보세요~

멋집니다.

그런데, 실행은 잘 되는데 Run 상태를 보니까 로그인이 안되는 것 같네요~!

**Comment by stateofai** [comment]
@dongbum 
헙.. 아까는 됐는데 안되네요. 수정 해놔야겠네요 ㅎㅎ

**Comment by stateofai** [comment]
@dongbum 님, 아래 실행 기록에는 또 정상 로그인이 되었네요. 일시적으로 문제가 발생하는 거 같긴 합니다
https://github.com/stateofai/naver-paper/actions/runs/7798741366/job/21268053387

**Comment by dongbum** [comment]
@stateofai 그러네요. 확인해보니 잘 됩니다.

감사합니다.
