### ISSUE TITLE
깃허브 액션으로 실행할 때 멀티계정으로는 안되나요?

### ISSUE THREAD

**Issue by dongbum** [stateofai/naver-paper#54]
깃허브 액션으로 실행할 때 멀티계정으로는 안되나요?

**Comment by bluesid** [comment]
@dongbum 님
secrets에 CREDENTIALENV 으로 json형태 추가하면 되도록 추가 해 뒀습니다.

**Comment by bluesid** [comment]
CREDENTIALENV 추가

**Comment by dongbum** [comment]
@bluesid 수정 작업 감사합니다.

그런데 방금 테스트 해봤는데 안되는 것 같네요... 액션은 잘 돌았는데 네이버 로그인이 안되는 것 같아요.

잘 작동하는건가요...?

**Comment by dongbum** [comment]
> CREDENTIALENV 추가

감사합니다!!!!!
